openapi: 3.0.0
info:
  title: Kupintar Auth API
  version: 0.1.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          description: User registered
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Login successful
  /auth/google:
    post:
      summary: Google OAuth login
      responses:
        '200':
          description: Google login successful
components:
  schemas:
    Register:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
