openapi: 3.0.0
info:
  title: Kupintar Profiles API
  version: 0.1.0
paths:
  /profiles/me:
    get:
      summary: Get current user's profile
      responses:
        '200':
          description: Profile details
    patch:
      summary: Update current user's profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
      responses:
        '200':
          description: Profile updated
components:
  schemas:
    ProfileUpdate:
      type: object
      properties:
        name:
          type: string
        avatar_url:
          type: string
